# Generated by Django 4.2.7 on 2024-01-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ('name',), 'verbose_name': 'furniture', 'verbose_name_plural': 'furniture'},
        ),
    ]
